### ISSUE TITLE
What is your #1 productivity tip? 

### ISSUE THREAD

**Issue by darrinhenein** [heatherpayne/ama#3]
You are known for making things happen. Enlighten us :)

**Comment by heatherpayne** [comment]
Hah - thanks, Darrin!

I don't know if I have one standout tip, but here are a few thoughts:

**1. Get enough sleep.** I sleep at least eight or nine hours every night, and I think it makes a huge difference when it comes to tackling my day.
**2. Focus.** For me, this isn't my natural instinct, but it's more of a trained ability that I've developed over time. By focusing on a small number of things, or even a single goal at a time, you can make a lot more progress toward it. 
**3. Go with the flow.** When you're "in the zone," you'll make more progress toward a goal than at any other time. I work hard when I'm in the zone, but I also don't force myself if I'm not feeling it.
**4. Develop leadership skills.** When it comes to getting stuff done, you'll only be able to get so far on your own. Through being an effective leader and empowering my team, HackerYou is able to accomplish infinitely more.
**5. Believe it's possible.** I do a lot of faking it until I make it. I don't let rules or beliefs or bullshit stop me from pursuing goals or dreams. I don't ask for permission, or wait until it's my turn. Not believing it's possible, or not dreaming big enough, holds a lot of people back from reaching their full potential.
